import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: "brown",
          color: "white",
          padding: "1rem",
          fontSize: "25px"
        }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer style={{
          backgroundColor: "black",
          color: "white",
          padding: "1rem",
          fontSize: "25px"
        }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
